import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "School App",
  description: "Generated by Shirly Studio",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body
      
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}<ToastContainer position="bottom-left" theme="dark"/>
      </body>
    </html>
  );
}
